[build]
  command = "npm run build:prod"
  publish = "dist/tsu-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.8.2"
