[build]
  command = "ng build --configuration=production"
  publish = "dist/tsu-app/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
